import type { Topic } from "../lib/types";

export const appTopics: Topic[] = [
  // ── TypeScript + React ─────────────────────────────────────────
  {
    id: "typescript-react",
    group: "app",
    name: "TypeScript + React",
    ja: "型安全{かたあんぜん}なUI開発",
    say: "タイプスクリプト・アンド・リアクト",
    oneLiner: {
      ja: "TypeScriptとReactで画面を作り、zodで外から来るデータを検証{けんしょう}します。",
      en: "I build the UI with TypeScript and React, and validate incoming data with zod.",
    },
    explain: [
      { ja: "フロントもサーバーも、TypeScriptで書いています。", en: "I write both the front end and the server in TypeScript." },
      { ja: "画面はReactのコンポーネントで作っています。", en: "The screens are built from React components." },
      { ja: "ただ、型はコンパイル時{じ}にしかチェックされません。", en: "But types are only checked at compile time." },
      { ja: "なので、外から来るデータはzodで検証{けんしょう}します。", en: "So data coming from outside is validated with zod." },
      { ja: "タイムラインはJSONで保存していて、スキーマで形を確かめます。", en: "The timeline is stored as JSON, and a schema checks its shape." },
      { ja: "スキーマから型も作れるので、定義{ていぎ}は一か所で済{す}みます。", en: "Types can be derived from the schema, so the definition lives in one place." },
      { ja: "編集の処理は純粋関数{じゅんすいかんすう}にして、packages/coreにまとめました。", en: "Editing logic is written as pure functions, collected in packages/core." },
      { ja: "だから、ブラウザがなくてもVitestでテストできます。", en: "That means it can be tested with Vitest without a browser." },
    ],
    why: [
      { ja: "Webとワーカーで、同じ型とルールを共有{きょうゆう}できるからです。", en: "Because the web app and the worker can share the same types and rules." },
      { ja: "DBのJSON列{れつ}は型がゆるいので、読む時にzodで確かめます。", en: "JSON columns in the DB are loosely typed, so I check them with zod when reading." },
      { ja: "トレードオフは、スキーマを保守{ほしゅ}する手間{てま}です。", en: "The trade-off is the effort of maintaining the schemas." },
      { ja: "でも、壊{こわ}れたデータで画面が落ちるよりはいいと考えました。", en: "But I judged that better than the screen crashing on broken data." },
    ],
    status: "built",
    statusNote: "Built and used everywhere: TypeScript across apps and packages, React 19 in the web app, zod 4 schemas in packages/core and in every Server Action.",
    inRepo: [
      { path: "packages/core/src/timeline.ts", what: "The zod timeline schema and the pure editing functions (split, trim, move)." },
      { path: "apps/web/components/editor/editor.tsx", what: "The client editor: useReducer with an undo/redo history." },
      { path: "apps/web/components/editor/history.ts", what: "Undo/redo as a stack of timeline snapshots." },
      { path: "packages/core/tests/timeline.test.ts", what: "Vitest tests for the editing rules, no browser needed." },
    ],
    terms: [
      { ja: "型安全{かたあんぜん}", en: "type safety" },
      { ja: "型推論{かたすいろん}", en: "type inference" },
      { ja: "実行時検証{じっこうじけんしょう}", en: "runtime validation", note: "Engineers also just say バリデーション or ランタイムバリデーション." },
      { ja: "スキーマ", en: "schema" },
      { ja: "純粋関数{じゅんすいかんすう}", en: "pure function", note: "Also 副作用{ふくさよう}のない関数, a function without side effects." },
      { ja: "状態管理{じょうたいかんり}", en: "state management" },
      { ja: "リデューサー", en: "reducer", note: "Said in katakana; nobody translates it." },
      { ja: "元{もと}に戻{もど}す／やり直{なお}す", en: "undo / redo", note: "In speech アンドゥ・リドゥ is just as common." },
      { ja: "コンポーネント", en: "component" },
      { ja: "型定義{かたていぎ}", en: "type definition" },
    ],
    qa: [
      {
        q: { ja: "なぜzodを使っているんですか？", en: "Why do you use zod?" },
        a: [
          { ja: "TypeScriptの型は、実行時には消えてしまいます。", en: "TypeScript types disappear at runtime." },
          { ja: "でも、ブラウザから来るデータは信用{しんよう}できません。", en: "But data coming from the browser can't be trusted." },
          { ja: "なので、Server Actionsの入口{いりぐち}でzodで検証{けんしょう}しています。", en: "So I validate it with zod at the entry of each Server Action." },
          { ja: "DBから読んだJSONも、同じスキーマで確かめます。", en: "JSON read from the DB is checked with the same schema." },
          { ja: "スキーマから型を作るので、型と検証がずれません。", en: "Types are derived from the schema, so types and validation never drift." },
        ],
        tip: "They want to hear that you know types are compile-time only. Mention z.infer: one source for both the type and the check.",
      },
      {
        q: { ja: "エディターの状態は、どう管理していますか？", en: "How do you manage the editor's state?" },
        a: [
          { ja: "タイムラインはuseReducerで持っています。", en: "The timeline is held in a useReducer." },
          { ja: "編集はすべて、packages/coreの純粋関数{じゅんすいかんすう}です。", en: "Every edit is a pure function from packages/core." },
          { ja: "undoとredoは、スナップショットのスタックで実装{じっそう}しました。", en: "Undo and redo are a stack of snapshots." },
          { ja: "スライダーの操作は、一回のundoにまとめています。", en: "A slider drag is merged into a single undo step." },
          { ja: "再生中{さいせいちゅう}の時刻{じこく}は、Reactのstateに入れていません。", en: "The playback time is not kept in React state." },
          { ja: "30fpsで再{さい}レンダリングしないためです。", en: "That avoids re-rendering the editor at 30 fps." },
        ],
        tip: "The playhead-outside-state detail shows real React performance experience. Say it if you have time.",
      },
      {
        q: { ja: "anyはどのくらい使いますか？", en: "How much do you use `any`?" },
        a: [
          { ja: "基本的には使いません。", en: "Basically never." },
          { ja: "外から来る値は、まずunknownとして受け取ります。", en: "Values from outside are received as unknown first." },
          { ja: "それをzodで検証{けんしょう}してから、型の付いた値にします。", en: "Then zod validates them and turns them into typed values." },
          { ja: "saveReelのtimelineも、unknownで受けてからパースしています。", en: "saveReel also takes the timeline as unknown and then parses it." },
        ],
        tip: "unknown + parse is the answer they hope for. saveSchema in apps/web/app/actions.ts really does use z.unknown().",
      },
    ],
    videoSearch: ["TypeScript React 入門 解説", "zod バリデーション TypeScript 解説", "useReducer 使い方 解説"],
    docs: [
      { title: "TypeScript ハンドブック (日本語)", url: "https://www.typescriptlang.org/ja/docs/handbook/intro.html" },
      { title: "React 公式ドキュメント (日本語)", url: "https://ja.react.dev/learn" },
      { title: "Zod", url: "https://zod.dev/" },
    ],
    related: ["nextjs", "server-actions", "vitest", "remotion"],
  },

  // ── Next.js ────────────────────────────────────────────────────
  {
    id: "nextjs",
    group: "app",
    name: "Next.js",
    ja: "Webアプリの土台{どだい}",
    say: "ネクストジェイエス",
    oneLiner: {
      ja: "Next.jsのApp Routerで、画面とサーバー処理を一つのアプリにまとめています。",
      en: "With the Next.js App Router, pages and server logic live in one app.",
    },
    explain: [
      { ja: "[Next.js]{ネクストジェイエス}は、Reactのフレームワークです。", en: "Next.js is a framework for React." },
      { ja: "ReelWalkでは、App Routerを使っています。", en: "ReelWalk uses the App Router." },
      { ja: "appフォルダの構成{こうせい}が、そのままURLになります。", en: "The structure of the app folder becomes the URLs." },
      { ja: "ページは基本的に、Server Componentsです。", en: "Pages are basically Server Components." },
      { ja: "画面用のREST APIは作っていません。", en: "There is no REST API for the UI." },
      { ja: "データの更新は、すべてServer Actionsで行います。", en: "All data changes go through Server Actions." },
      { ja: "Route Handlerは、ヘルスチェックなど一部{いちぶ}だけです。", en: "Route Handlers are used only in a few places, like health checks." },
      { ja: "ビルドはstandalone出力{しゅつりょく}で、Dockerイメージを小さくしています。", en: "The build uses standalone output to keep the Docker image small." },
    ],
    why: [
      { ja: "画面とAPIを別々に作らなくていいので、コードが減{へ}ります。", en: "I don't have to build pages and an API separately, so there is less code." },
      { ja: "フルスタックを、一つのTypeScriptプロジェクトで書けます。", en: "The whole stack is one TypeScript project." },
      { ja: "トレードオフは、Next.js独自{どくじ}の約束事{やくそくごと}が多いことです。", en: "The trade-off is that Next.js has many conventions of its own." },
      { ja: "キャッシュの動きも、バージョンによってよく変わります。", en: "Caching behaviour also changes often between versions." },
    ],
    status: "built",
    statusNote: "Built with Next.js 16 and runs locally (dev server, Docker Compose, kind); it has never been deployed to AWS.",
    inRepo: [
      { path: "apps/web/app/page.tsx", what: "The reels grid: an async Server Component that queries Prisma directly." },
      { path: "apps/web/app/api/health", what: "Route Handlers kept only for Kubernetes probes (health, ready) and the timeline editor." },
      { path: "apps/web/next.config.ts", what: "Standalone output and transpilePackages for the workspace packages." },
      { path: "apps/web/Dockerfile", what: "The web image built from the standalone output." },
    ],
    terms: [
      { ja: "フレームワーク", en: "framework" },
      { ja: "ルーティング", en: "routing" },
      { ja: "レイアウト", en: "layout (layout.tsx, shared around pages)" },
      { ja: "動的{どうてき}レンダリング", en: "dynamic rendering", note: "ReelWalk pages set `dynamic = \"force-dynamic\"` because every request reads the DB." },
      { ja: "再検証{さいけんしょう}", en: "revalidation", note: "revalidatePath after a mutation. Engineers often just say リバリデート." },
      { ja: "ルートハンドラー", en: "Route Handler" },
      { ja: "ヘルスチェック", en: "health check" },
      { ja: "プリフェッチ", en: "prefetch" },
      { ja: "出力{しゅつりょく}", en: "output (build output)" },
    ],
    qa: [
      {
        q: { ja: "なぜNext.jsのApp Routerを選んだんですか？", en: "Why did you choose the Next.js App Router?" },
        a: [
          { ja: "一番の理由は、Server ComponentsとServer Actionsです。", en: "The main reason is Server Components and Server Actions." },
          { ja: "ページの中で、直接{ちょくせつ}Prismaを呼べます。", en: "Pages can call Prisma directly." },
          { ja: "更新もServer Actionsなので、UI用のAPIがいりません。", en: "Mutations are Server Actions too, so no API is needed for the UI." },
          { ja: "一人で作るには、コードが少ないのが大事でした。", en: "Building it alone, having less code mattered a lot." },
        ],
        tip: "Tie the choice to a concrete benefit (no separate API layer). Craftsman uses Server Components/Actions too, so you can say you used them in a real app.",
      },
      {
        q: { ja: "Route Handlerは、どこで使っていますか？", en: "Where do you use Route Handlers?" },
        a: [
          { ja: "呼{よ}び出{だ}し元{もと}が、このアプリのUIじゃない時だけです。", en: "Only when the caller is not this app's UI." },
          { ja: "/api/healthと/api/readyは、Kubernetesのプローブ用です。", en: "/api/health and /api/ready are for Kubernetes probes." },
          { ja: "あとは、別のタイムラインエディター用のエンドポイントが一つです。", en: "Besides that, one endpoint for the separate timeline editor." },
          { ja: "それ以外は、すべてServer Actionsです。", en: "Everything else is a Server Action." },
        ],
        tip: "Shows you know when each tool fits: Server Actions for your own UI, Route Handlers for external callers.",
      },
      {
        q: { ja: "パフォーマンスで工夫{くふう}したことはありますか？", en: "Did you do anything for performance?" },
        a: [
          { ja: "リール一覧{いちらん}のリンクは、プリフェッチを切っています。", en: "I turned off prefetch on the links in the reels list." },
          { ja: "エディターのページは重いので、全部のカードが先読{さきよ}みしていました。", en: "Editor pages are heavy, and every card was prefetching one." },
          { ja: "ブラウザの同時接続{どうじせつぞく}が埋{う}まって、次の操作が待たされたんです。", en: "That filled the browser's concurrent connections, and the next tap had to wait." },
          { ja: "署名付{しょめいつ}きURLも、寿命{じゅみょう}の半分まで使い回{まわ}しています。", en: "Signed URLs are also reused for the first half of their lifetime." },
          { ja: "URLが変わると、ブラウザが動画を読み直すからです。", en: "Because if the URL changes, the browser reloads the video." },
        ],
        tip: "A real bug you found and fixed beats generic advice. Both are in the code (prefetch={false} in app/page.tsx, the signedUrls map in lib/storage.ts).",
      },
    ],
    videoSearch: ["Next.js App Router 入門 解説", "Next.js 16 新機能 解説", "Next.js standalone Docker 解説"],
    docs: [
      { title: "Next.js Docs: App Router", url: "https://nextjs.org/docs/app" },
      { title: "Next.js: Route Handlers", url: "https://nextjs.org/docs/app/api-reference/file-conventions/route" },
      { title: "Next.js: output (standalone)", url: "https://nextjs.org/docs/app/api-reference/config/next-config-js/output" },
    ],
    related: ["server-components", "server-actions", "typescript-react", "docker", "kubernetes"],
  },

  // ── Server Components ──────────────────────────────────────────
  {
    id: "server-components",
    group: "app",
    name: "Server Components",
    ja: "サーバーで描画{びょうが}する部品",
    say: "サーバーコンポーネント",
    oneLiner: {
      ja: "データ込みでサーバーで描画{びょうが}し、操作する部分だけをクライアントにします。",
      en: "Render on the server with the data included; only the interactive parts go to the client.",
    },
    explain: [
      { ja: "Server Componentsは、サーバーだけで動くコンポーネントです。", en: "Server Components are components that run only on the server." },
      { ja: "async関数として書けて、中でPrismaを直接{ちょくせつ}呼べます。", en: "They can be async functions and call Prisma directly." },
      { ja: "ブラウザにJavaScriptを送らないので、軽いです。", en: "They send no JavaScript to the browser, so they are light." },
      { ja: "一方{いっぽう}、Client Componentsはブラウザで動きます。", en: "Client Components, on the other hand, run in the browser." },
      { ja: "stateやイベントが必要なら、「use client」を付けます。", en: "If you need state or events, you add \"use client\"." },
      { ja: "エディターのページが、いい例{れい}です。", en: "The editor page is a good example." },
      { ja: "サーバーでリールとメディアを読んで、propsで渡します。", en: "The server loads the reel and its media and passes them as props." },
      { ja: "編集の操作は、Client ComponentのEditorが担当{たんとう}します。", en: "The editing itself is handled by the Editor Client Component." },
    ],
    why: [
      { ja: "データ取得{しゅとく}のためのAPI層{そう}が、いらなくなります。", en: "There is no need for an API layer just to fetch data." },
      { ja: "DBの接続情報{せつぞくじょうほう}が、ブラウザに出ることもありません。", en: "DB connection details never reach the browser." },
      { ja: "トレードオフは、境界{きょうかい}を意識{いしき}する必要があることです。", en: "The trade-off is that you have to keep the boundary in mind." },
      { ja: "渡せるpropsは、シリアライズできる値だけです。", en: "Only serializable values can be passed as props." },
    ],
    status: "built",
    statusNote: "Built: the reels grid, editor page, export screen and exports list are async Server Components reading Postgres through Prisma; runs locally only.",
    inRepo: [
      { path: "apps/web/app/reels/[id]/page.tsx", what: "Server Component loads the reel, library and floor plans, then renders the client Editor." },
      { path: "apps/web/components/editor/editor.tsx", what: "The \"use client\" boundary: the interactive editor." },
      { path: "apps/web/components/auto-refresh.tsx", what: "Tiny client component that calls router.refresh() every 2 s while a render is active." },
      { path: "apps/web/lib/workspace.ts", what: "getCurrentUser wrapped in React cache(), so one request queries the user once." },
    ],
    terms: [
      { ja: "サーバーコンポーネント", en: "Server Component", note: "Often shortened to RSC (アールエスシー)." },
      { ja: "クライアントコンポーネント", en: "Client Component" },
      { ja: "境界{きょうかい}", en: "boundary (the \"use client\" line)" },
      { ja: "シリアライズ", en: "serialize", note: "Kanji form 直列化{ちょくれつか} exists but engineers say シリアライズ." },
      { ja: "ハイドレーション", en: "hydration" },
      { ja: "バンドルサイズ", en: "bundle size" },
      { ja: "データ取得{しゅとく}", en: "data fetching", note: "Also データフェッチ." },
      { ja: "描画{びょうが}", en: "rendering, drawing", note: "レンダリング is more common for React; 描画 is the kanji word." },
      { ja: "再{さい}レンダリング", en: "re-render" },
    ],
    qa: [
      {
        q: { ja: "Server ComponentsとClient Componentsの違いは何ですか？", en: "What's the difference between Server and Client Components?" },
        a: [
          { ja: "Server Componentsは、サーバーだけで実行されます。", en: "Server Components run only on the server." },
          { ja: "DBに直接アクセスできて、JSはブラウザに送られません。", en: "They can access the DB directly, and no JS is sent to the browser." },
          { ja: "Client Componentsは、ブラウザでも動きます。", en: "Client Components also run in the browser." },
          { ja: "stateやクリックなどの操作が必要な時に使います。", en: "I use them when I need state or interactions like clicks." },
          { ja: "ReelWalkでは、データはサーバー、操作はクライアントと分けています。", en: "In ReelWalk, data stays on the server and interaction on the client." },
        ],
        tip: "Give the rule and then one concrete example from your app (editor page loads data, Editor is the client component).",
      },
      {
        q: { ja: "レンダリングの進捗{しんちょく}は、どうやって画面に出していますか？", en: "How do you show render progress on screen?" },
        a: [
          { ja: "ワーカーが進捗を、PostgreSQLに直接書きます。", en: "The worker writes progress straight to PostgreSQL." },
          { ja: "画面はServer Componentなので、DBの値をそのまま表示{ひょうじ}します。", en: "The page is a Server Component, so it just shows the DB value." },
          { ja: "ジョブが動いている間だけ、2秒ごとにrouter.refreshを呼びます。", en: "Only while a job is running, it calls router.refresh every 2 seconds." },
          { ja: "クライアント側{がわ}に、データ取得{しゅとく}の仕組{しく}みはいりません。", en: "No data-fetching layer is needed on the client." },
        ],
        tip: "Polling via router.refresh is simple and honest. If asked about WebSockets or SSE, say it would be the next step at higher scale.",
      },
      {
        q: { ja: "どこまでをClient Componentにしましたか？", en: "How much did you make into Client Components?" },
        a: [
          { ja: "できるだけ小さくしています。", en: "As little as possible." },
          { ja: "エディター、共有{きょうゆう}ボタン、タブバーなど、操作がある部分だけです。", en: "Only interactive parts: the editor, the share button, the tab bar and so on." },
          { ja: "一覧{いちらん}や書{か}き出{だ}し画面は、Server Componentです。", en: "The lists and the export screen are Server Components." },
        ],
        tip: "\"Push the client boundary down\" is the standard best practice; say it in your own words.",
      },
    ],
    videoSearch: ["React Server Components 解説", "Next.js Server Components Client Components 違い", "RSC 仕組み 解説"],
    docs: [
      { title: "React: サーバコンポーネント (日本語)", url: "https://ja.react.dev/reference/rsc/server-components" },
      { title: "React: 'use client' (日本語)", url: "https://ja.react.dev/reference/rsc/use-client" },
      { title: "Next.js: Server and Client Components", url: "https://nextjs.org/docs/app/getting-started/server-and-client-components" },
    ],
    related: ["nextjs", "server-actions", "prisma", "postgresql"],
  },

  // ── Server Actions ─────────────────────────────────────────────
  {
    id: "server-actions",
    group: "app",
    name: "Server Actions",
    ja: "サーバー側{がわ}の更新処理",
    say: "サーバーアクション",
    oneLiner: {
      ja: "更新はすべてServer Actionsで、入口{いりぐち}で検証{けんしょう}と権限{けんげん}を確認します。",
      en: "Every update is a Server Action that checks input and permissions at the entry point.",
    },
    explain: [
      { ja: "Server Actionsは、サーバーの関数をブラウザから呼べる仕組{しく}みです。", en: "Server Actions let the browser call a function on the server." },
      { ja: "ReelWalkでは、データの更新はすべてServer Actionsです。", en: "In ReelWalk, every data change is a Server Action." },
      { ja: "リールの作成{さくせい}、保存、アップロード、書{か}き出{だ}しなどです。", en: "Creating a reel, saving, uploading, exporting, and so on." },
      { ja: "入口{いりぐち}では、必ずzodで入力を検証{けんしょう}します。", en: "At the entry point, input is always validated with zod." },
      { ja: "クエリには、必ずworkspaceIdを条件に入れます。", en: "Every query includes workspaceId as a condition." },
      { ja: "保存には、リビジョン番号を使っています。", en: "Saving uses a revision number." },
      { ja: "古いリビジョンからの保存は、拒否{きょひ}されます。", en: "A save from an old revision is rejected." },
      { ja: "別のタブの変更を、黙{だま}って上書{うわが}きしないためです。", en: "So that another tab's changes are never silently overwritten." },
    ],
    why: [
      { ja: "フォームやfetch用のAPIを、別に作らなくて済みます。", en: "I don't need a separate API for forms or fetch calls." },
      { ja: "引数{ひきすう}と戻{もど}り値の型が、そのままクライアントにつながります。", en: "Argument and return types flow straight through to the client." },
      { ja: "ただ、リクエストボディのサイズに制限{せいげん}があります。", en: "But there is a limit on the request body size." },
      { ja: "なので、大きな動画はServer Actionsを通さず、S3に直接送ります。", en: "So large videos skip Server Actions and go straight to S3." },
    ],
    status: "built",
    statusNote: "Built: createReel, saveReel (revision check), saveCaption, createUpload, confirmUpload, exportReel and retryRenderJob are real; there is no login yet, so the workspace comes from a seeded demo user.",
    inRepo: [
      { path: "apps/web/app/actions.ts", what: "Every Server Action; see saveReel for the revision check and retryRenderJob for a conditional retry." },
      { path: "apps/web/components/editor/use-autosave.ts", what: "Calls saveReel 700 ms after an edit with the last revision it saw." },
      { path: "apps/web/lib/workspace.ts", what: "getCurrentUser: the one place to swap in real auth later." },
      { path: "packages/core/src/instagram.ts", what: "Instagram rules, re-checked on the server inside exportReel." },
    ],
    terms: [
      { ja: "サーバーアクション", en: "Server Action", note: "React now calls these Server Functions (サーバー関数)." },
      { ja: "更新処理", en: "mutation", note: "ミューテーション is also used." },
      { ja: "入力検証{にゅうりょくけんしょう}", en: "input validation", note: "Often just バリデーション." },
      { ja: "楽観的{らっかんてき}ロック", en: "optimistic locking", note: "The revision check is optimistic concurrency control." },
      { ja: "競合{きょうごう}", en: "conflict", note: "コンフリクト is also common." },
      { ja: "上書{うわが}き", en: "overwrite" },
      { ja: "認可{にんか}", en: "authorization", note: "認証{にんしょう} is authentication. Don't mix them up." },
      { ja: "条件付{じょうけんつ}き更新", en: "conditional update" },
      { ja: "自動保存", en: "autosave", note: "オートセーブ is also fine." },
    ],
    qa: [
      {
        q: { ja: "リビジョンチェックは、どう実装{じっそう}しましたか？", en: "How did you implement the revision check?" },
        a: [
          { ja: "ブラウザは、最後に見たリビジョンを一緒に送ります。", en: "The browser sends the last revision it saw along with the save." },
          { ja: "サーバーは、updateManyのwhereにそのリビジョンを入れます。", en: "The server puts that revision in the where clause of updateMany." },
          { ja: "成功したら、リビジョンを1つ増やします。", en: "On success, the revision is incremented by one." },
          { ja: "更新件数{こうしんけんすう}が0なら、別のタブが先に保存したということです。", en: "If zero rows changed, another tab saved first." },
          { ja: "その時は上書きせず、再読{さいよ}み込みをお願いします。", en: "Then it doesn't overwrite, and asks the user to reload." },
        ],
        tip: "Name it: 楽観的ロック (optimistic locking). Mention it's one SQL statement, no read-then-write, no explicit lock.",
      },
      {
        q: { ja: "Server Actionsのセキュリティで、気をつけていることは？", en: "What do you watch out for with Server Actions security?" },
        a: [
          { ja: "Server Actionsは、実質{じっしつ}的に公開{こうかい}されたエンドポイントです。", en: "A Server Action is effectively a public endpoint." },
          { ja: "なので、入力は必ずzodで検証{けんしょう}します。", en: "So input is always validated with zod." },
          { ja: "クエリは全部、ワークスペースで絞{しぼ}り込みます。", en: "Every query is scoped to the workspace." },
          { ja: "保存の時は、使っているメディアが同じワークスペースのものかも確認します。", en: "On save I also check the media used belongs to the same workspace." },
          { ja: "ただ、ログインはまだなく、デモユーザーで動いています。", en: "But there's no login yet; it runs as a demo user." },
        ],
        tip: "Being upfront that auth is missing (and that it's isolated in one function) reads as maturity, not weakness.",
      },
      {
        q: { ja: "書{か}き出{だ}しの時、サーバーでは何をしていますか？", en: "What does the server do on export?" },
        a: [
          { ja: "まず、Instagramのルールをサーバーでもう一度チェックします。", en: "First it re-checks the Instagram rules on the server." },
          { ja: "次に、その時点のタイムラインをジョブに保存します。", en: "Next it saves the timeline as of that moment into the job." },
          { ja: "後で編集しても、書き出す動画は変わりません。", en: "Later edits don't change the video being exported." },
          { ja: "最後に、キューにメッセージを送ります。", en: "Finally it sends a message to the queue." },
          { ja: "送信に失敗したら、ジョブをFAILEDにして再試行{さいしこう}できるようにします。", en: "If sending fails, the job is marked FAILED so it can be retried." },
        ],
        tip: "Freezing the payload makes retries deterministic. Link to the queue and idempotency topics if they dig in.",
      },
    ],
    videoSearch: ["Next.js Server Actions 解説", "Server Actions zod バリデーション", "楽観的ロック 解説"],
    docs: [
      { title: "React: サーバ関数 (日本語)", url: "https://ja.react.dev/reference/rsc/server-functions" },
      { title: "Next.js: Updating Data (Server Actions)", url: "https://nextjs.org/docs/app/getting-started/updating-data" },
      { title: "Next.js: Data Security", url: "https://nextjs.org/docs/app/guides/data-security" },
    ],
    related: ["server-components", "typescript-react", "postgresql", "s3", "sqs", "idempotency"],
  },

  // ── Remotion ───────────────────────────────────────────────────
  {
    id: "remotion",
    group: "app",
    name: "Remotion",
    ja: "Reactで動画を作る",
    say: "リモーション",
    oneLiner: {
      ja: "一つのReactコンポーネントで、プレビューと書{か}き出{だ}しの両方{りょうほう}を描{えが}きます。",
      en: "One React component draws both the live preview and the exported video.",
    },
    explain: [
      { ja: "[Remotion]{リモーション}は、Reactで動画を作るライブラリです。", en: "Remotion is a library for making video with React." },
      { ja: "フレーム番号から、その瞬間{しゅんかん}の画面を描{えが}きます。", en: "From a frame number, it draws the picture for that moment." },
      { ja: "ReelWalkでは、ReelCompositionがリールを描きます。", en: "In ReelWalk, ReelComposition draws a reel." },
      { ja: "エディターでは、@remotion/playerでプレビューします。", en: "In the editor, it's previewed with @remotion/player." },
      { ja: "書き出しでは、ワーカーが同じコンポーネントをレンダリングします。", en: "On export, the worker renders the same component." },
      { ja: "中ではヘッドレスChromeとffmpegが動いています。", en: "Inside, headless Chrome and ffmpeg do the work." },
      { ja: "だから、スマホで見たものと動画がずれません。", en: "So the video matches what you saw on the phone." },
      { ja: "違{ちが}いは、動画のデコード方法だけです。", en: "The only difference is how video is decoded." },
    ],
    why: [
      { ja: "プレビューと書き出しを別々に作ると、だんだんずれていきます。", en: "If preview and export are built separately, they drift apart." },
      { ja: "一つのコンポーネントなら、機能を一回書くだけで済みます。", en: "With one component, each feature is written once." },
      { ja: "トレードオフは、ワーカーのイメージが約1.5GBと大きいことです。", en: "The trade-off is a large worker image, about 1.5 GB." },
      { ja: "それと、4人以上の会社では有料{ゆうりょう}ライセンスが必要です。", en: "Also, companies of four or more people need a paid licence." },
    ],
    status: "built",
    statusNote: "Built: the Player preview and worker renders to MP4 both work locally and in the Playwright e2e run; ADR 0006 records the decision.",
    inRepo: [
      { path: "packages/render/src/reel/ReelComposition.tsx", what: "The one composition used by both the Player and the worker." },
      { path: "apps/web/components/editor/preview.tsx", what: "The editor preview using <Player> from @remotion/player." },
      { path: "packages/render/src/render-reel.ts", what: "Worker side: bundle, selectComposition and renderMedia to MP4." },
      { path: "docs/adr/0006-one-composition-for-preview-and-export.md", what: "Why one composition, and the rejected alternatives." },
    ],
    terms: [
      { ja: "コンポジション", en: "composition (Remotion's unit of video)" },
      { ja: "プレビュー", en: "preview" },
      { ja: "書{か}き出{だ}し", en: "export (rendering the final file)", note: "エクスポート is equally common." },
      { ja: "ヘッドレスブラウザ", en: "headless browser" },
      { ja: "フレーム", en: "frame" },
      { ja: "デコード", en: "decode", note: "Kanji form 復号{ふくごう} is for cryptography; for video say デコード." },
      { ja: "縦型{たてがた}動画", en: "vertical video (9:16)" },
      { ja: "並列度{へいれつど}", en: "degree of concurrency", note: "RENDER_CONCURRENCY. Engineers also say 並列数{へいれつすう}." },
      { ja: "安全領域{あんぜんりょういき}", en: "safe zone", note: "セーフゾーン is what people actually say." },
    ],
    qa: [
      {
        q: { ja: "なぜスマホの中で書{か}き出{だ}さないんですか？", en: "Why not export on the phone itself?" },
        a: [
          { ja: "サーバー代はかかりませんが、中くらいのスマホだと遅いです。", en: "It costs nothing on the server, but it's slow on mid-range phones." },
          { ja: "画面がロックされると、止まってしまいます。", en: "It stops when the screen locks." },
          { ja: "それに、失敗した時に再試行{さいしこう}するジョブが残りません。", en: "And when it fails, there's no job left to retry." },
          { ja: "なので、書き出しはサーバーのワーカーでやっています。", en: "So exports run on a worker on the server." },
        ],
        tip: "Show you weighed the cheaper option. The older desktop editor (apps/editor) does in-browser export, so you know both.",
      },
      {
        q: { ja: "プレビューと書き出しで、違いはありますか？", en: "Are there differences between preview and export?" },
        a: [
          { ja: "動画のデコードだけ違います。", en: "Only video decoding differs." },
          { ja: "プレビューは普通{ふつう}のvideo要素{ようそ}で、スマホのハードウェアを使います。", en: "The preview uses a plain video element with the phone's hardware decoder." },
          { ja: "ワーカーは@remotion/mediaで、WebCodecsを使います。", en: "The worker uses @remotion/media, which uses WebCodecs." },
          { ja: "測{はか}ったら、OffthreadVideoの約2倍速{ばいそく}でした。", en: "When I measured it, it was about twice as fast as OffthreadVideo." },
          { ja: "フォントやフィルターは同じなので、見た目は一致{いっち}します。", en: "Fonts and filters are the same, so the look matches." },
        ],
        tip: "\"I measured it\" is strong. Keep the number modest and say it was a local measurement.",
      },
      {
        q: { ja: "レンダリングを速くするには、どうしますか？", en: "How would you make rendering faster?" },
        a: [
          { ja: "時間のほとんどは、動画のデコードです。", en: "Most of the time goes into decoding video." },
          { ja: "一つのレンダリングの中では、RENDER_CONCURRENCYで並列度{へいれつど}を上げます。", en: "Within one render, RENDER_CONCURRENCY raises the parallelism." },
          { ja: "全体{ぜんたい}としては、ワーカーのPodを増やしてスケールアウトします。", en: "Overall, I scale out by adding worker pods." },
          { ja: "キューの長さでスケールするKEDAは、次の課題{かだい}です。", en: "Scaling on queue depth with KEDA is the next step." },
        ],
        tip: "Separate scale-up (concurrency per render) from scale-out (more pods). KEDA is planned, not built.",
      },
    ],
    videoSearch: ["Remotion React 動画 作成 解説", "Remotion 入門", "React で動画編集 Remotion"],
    docs: [
      { title: "Remotion: <Player>", url: "https://www.remotion.dev/docs/player" },
      { title: "Remotion: renderMedia()", url: "https://www.remotion.dev/docs/renderer/render-media" },
      { title: "Remotion: License", url: "https://www.remotion.dev/docs/license" },
    ],
    related: ["worker", "typescript-react", "sqs", "docker", "playwright"],
  },

  // ── Prisma ─────────────────────────────────────────────────────
  {
    id: "prisma",
    group: "data",
    name: "Prisma",
    ja: "型付{かたつ}きのDBアクセス",
    say: "プリズマ",
    oneLiner: {
      ja: "DBの定義と型付{かたつ}きクライアントを、Webとワーカーで共有{きょうゆう}します。",
      en: "The DB definition and a typed client are shared by the web app and the worker.",
    },
    explain: [
      { ja: "[Prisma]{プリズマ}は、TypeScript向けのORMです。", en: "Prisma is an ORM for TypeScript." },
      { ja: "schema.prismaに、モデルを書きます。", en: "You write the models in schema.prisma." },
      { ja: "そこから、型付{かたつ}きのクライアントが生成{せいせい}されます。", en: "A typed client is generated from it." },
      { ja: "スキーマとマイグレーションは、packages/dbにあります。", en: "The schema and migrations live in packages/db." },
      { ja: "Webとワーカーが、同じクライアントを使っています。", en: "The web app and the worker use the same client." },
      { ja: "マイグレーションは、SQLファイルとしてコミットします。", en: "Migrations are committed as SQL files." },
      { ja: "クラスタでは、KubernetesのJobで適用{てきよう}します。", en: "On the cluster, a Kubernetes Job applies them." },
      { ja: "アプリが更新される前に、prisma migrate deployが走ります。", en: "prisma migrate deploy runs before the app is updated." },
    ],
    why: [
      { ja: "一番の理由は、Webとワーカーで型を共有できることです。", en: "The main reason is sharing types between web and worker." },
      { ja: "最初はasyncpgで生{なま}のSQLを書いていましたが、型が共有できませんでした。", en: "The first version used raw SQL with asyncpg, but types couldn't be shared." },
      { ja: "トレードオフは、generateを先に実行しないと型エラーになることです。", en: "The trade-off is that you get type errors unless generate runs first." },
      { ja: "Prisma 7では、ドライバーアダプターも必要になりました。", en: "Prisma 7 also requires a driver adapter." },
    ],
    status: "built",
    statusNote: "Built: Prisma 7 with @prisma/adapter-pg, five committed migrations, and a migrate Job in the Helm chart that has run on kind; never run against RDS.",
    inRepo: [
      { path: "packages/db/prisma/schema.prisma", what: "All models: Workspace, User, Reel, MediaAsset, Tour, RenderJob, RenderOutput." },
      { path: "packages/db/prisma/migrations", what: "Committed SQL migrations applied with migrate deploy." },
      { path: "packages/db/src/index.ts", what: "The shared client with the pg adapter, kept on globalThis in dev." },
      { path: "infra/helm/reelwalk/templates/migrate-job.yaml", what: "The one-shot migrate Job (Argo CD sync-wave -1, name hashed per release)." },
    ],
    terms: [
      { ja: "ORM", en: "object-relational mapper", note: "Read オーアールエム." },
      { ja: "マイグレーション", en: "migration", note: "The kanji word 移行{いこう} is used for data migration in general; for schema changes say マイグレーション." },
      { ja: "型付{かたつ}きクライアント", en: "typed client" },
      { ja: "コード生成{せいせい}", en: "code generation" },
      { ja: "ドライバーアダプター", en: "driver adapter" },
      { ja: "シード", en: "seed data", note: "Also 初期{しょき}データ." },
      { ja: "接続{せつぞく}プール", en: "connection pool", note: "コネクションプール is also common." },
      { ja: "アップサート", en: "upsert (insert or update)" },
      { ja: "適用{てきよう}する", en: "to apply (a migration)" },
    ],
    qa: [
      {
        q: { ja: "マイグレーションは、どう運用していますか？", en: "How do you run migrations?" },
        a: [
          { ja: "開発中は、prisma migrate devでSQLを作ってコミットします。", en: "During development, prisma migrate dev creates the SQL and I commit it." },
          { ja: "クラスタでは、HelmのJobがmigrate deployを実行します。", en: "On the cluster, a Helm Job runs migrate deploy." },
          { ja: "Argo CDでは、このJobが先に終わるようにしています。", en: "With Argo CD, this Job is made to finish first." },
          { ja: "Jobの名前にハッシュを入れて、リリースごとに作り直します。", en: "The Job name includes a hash, so each release creates a new one." },
          { ja: "これはkindで検証{けんしょう}しました。", en: "I verified this on kind." },
        ],
        tip: "Mention the Job pod template is immutable, which is why the name carries a hash. Say kind, not EKS.",
      },
      {
        q: { ja: "Prismaを使ってみて、困ったことはありますか？", en: "Any problems using Prisma?" },
        a: [
          { ja: "クライアントがリポジトリの中に生成されることです。", en: "The client is generated into the repository tree." },
          { ja: "generateを忘れると、型チェックもテストも失敗します。", en: "If you forget generate, typecheck and tests both fail." },
          { ja: "なので、Turborepoで最初に実行されるようにしました。", en: "So I made Turborepo run it first." },
          { ja: "もう一つは、Next.jsの開発中に接続{せつぞく}が増えることです。", en: "Another was connections piling up during Next.js development." },
          { ja: "クライアントをglobalThisに置いて、一つだけにしています。", en: "I keep the client on globalThis so there's only one." },
        ],
        tip: "Concrete pain + concrete fix. Both fixes are visible in turbo.json and packages/db/src/index.ts.",
      },
    ],
    videoSearch: ["Prisma 入門 解説", "Prisma マイグレーション 解説", "Prisma Next.js 使い方"],
    docs: [
      { title: "Prisma Migrate", url: "https://www.prisma.io/docs/orm/prisma-migrate" },
      { title: "Prisma Client", url: "https://www.prisma.io/docs/orm/prisma-client" },
      { title: "Prisma: Deploying migrations", url: "https://www.prisma.io/docs/orm/prisma-client/deployment/deploy-database-changes-with-prisma-migrate" },
    ],
    related: ["postgresql", "turborepo", "helm", "argocd", "kind", "typescript-react"],
  },

  // ── PostgreSQL ─────────────────────────────────────────────────
  {
    id: "postgresql",
    group: "data",
    name: "PostgreSQL",
    ja: "信頼{しんらい}できる唯一{ゆいいつ}の情報源{じょうほうげん}",
    say: "ポストグレスキューエル",
    oneLiner: {
      ja: "データの正{せい}はPostgreSQLで、状態は条件付{じょうけんつ}きUPDATEで変えます。",
      en: "PostgreSQL is the source of truth, and state changes are conditional UPDATEs.",
    },
    explain: [
      { ja: "データの正{せい}は、PostgreSQLに置いています。", en: "PostgreSQL holds the source of truth." },
      { ja: "リール、メディア、ジョブ、出力{しゅつりょく}が全部入っています。", en: "Reels, media, jobs and outputs are all in it." },
      { ja: "キューのメッセージは、ジョブIDと世代{せだい}だけです。", en: "Queue messages carry only the job ID and its generation." },
      { ja: "状態は、いつもDBの行{ぎょう}を見て判断{はんだん}します。", en: "State is always decided by looking at the DB row." },
      { ja: "ステータスの変更は、条件付{じょうけんつ}きのUPDATE一回です。", en: "A status change is a single conditional UPDATE." },
      { ja: "WHERE句{く}に、今のステータスと世代を入れます。", en: "The WHERE clause includes the current status and generation." },
      { ja: "誰かが先に更新していたら、0行になるだけです。", en: "If someone updated it first, zero rows change, that's all." },
      { ja: "読んでから書く処理がないので、ロックはいりません。", en: "There's no read-then-write, so no locks are needed." },
    ],
    why: [
      { ja: "データがリレーショナルで、ジョインが必要だからです。", en: "Because the data is relational and needs joins." },
      { ja: "DynamoDBも考えましたが、アクセスパターンがまだ固{かた}まっていませんでした。", en: "I considered DynamoDB, but the access patterns weren't settled yet." },
      { ja: "AWSではRDSを使う設計で、変わるのはDATABASE_URLだけです。", en: "The AWS design uses RDS; only DATABASE_URL changes." },
      { ja: "トレードオフは、接続数{せつぞくすう}やスケールを自分で考える必要があることです。", en: "The trade-off is having to think about connection counts and scaling yourself." },
    ],
    status: "built",
    statusNote: "Built: PostgreSQL 16 runs locally in Docker Compose and kind, and the conditional updates are real and tested; RDS exists only as a Terraform sketch that was never applied.",
    inRepo: [
      { path: "apps/worker/src/store.ts", what: "Every job status change as one conditional updateMany; succeed() wraps upsert + update in a transaction." },
      { path: "packages/core/src/job-status.ts", what: "The legal state transitions as a pure function, covered by Vitest." },
      { path: "docs/adr/0002-postgresql-and-prisma.md", what: "Why PostgreSQL + Prisma, and why not DynamoDB or raw SQL." },
      { path: "infra/terraform/main.tf", what: "The aws_db_instance sketch (postgres 16, db.t4g.micro), never applied." },
    ],
    terms: [
      { ja: "リレーショナルデータベース", en: "relational database", note: "Often RDB (アールディービー). PostgreSQL itself is nicknamed ポスグレ." },
      { ja: "条件付{じょうけんつ}き更新", en: "conditional update" },
      { ja: "競合状態{きょうごうじょうたい}", en: "race condition", note: "レースコンディション is also used." },
      { ja: "排他制御{はいたせいぎょ}", en: "mutual exclusion / concurrency control" },
      { ja: "楽観的{らっかんてき}ロック", en: "optimistic locking" },
      { ja: "トランザクション", en: "transaction" },
      { ja: "世代{せだい}", en: "generation (the retry counter on a job)" },
      { ja: "正{せい}のデータ", en: "source of truth", note: "Also 信頼{しんらい}できる唯一{ゆいいつ}の情報源{じょうほうげん}, or just SSOT." },
      { ja: "マネージドサービス", en: "managed service (like RDS)" },
    ],
    qa: [
      {
        q: { ja: "二つのワーカーが同じジョブを取ったら、どうなりますか？", en: "What happens if two workers pick up the same job?" },
        a: [
          { ja: "両方{りょうほう}がupdateManyで、RUNNINGにしようとします。", en: "Both try to set it to RUNNING with updateMany." },
          { ja: "WHEREには、QUEUEDか、ハートビートが古いRUNNINGを入れています。", en: "The WHERE accepts QUEUED, or RUNNING with a stale heartbeat." },
          { ja: "先に書いた方だけが、1行更新できます。", en: "Only the one that writes first updates one row." },
          { ja: "もう一方{いっぽう}は0行なので、何もしません。", en: "The other gets zero rows, so it does nothing." },
          { ja: "DBが判定{はんてい}するので、アプリ側でロックはいりません。", en: "The DB decides, so the app needs no lock." },
        ],
        tip: "This is the core of the design. Draw it on paper if there's a whiteboard: WHERE status/generation is the guard.",
      },
      {
        q: { ja: "トランザクションは使っていますか？", en: "Do you use transactions?" },
        a: [
          { ja: "完了{かんりょう}の時は、出力の保存とステータス更新を一つのトランザクションにしています。", en: "On completion, saving the output and updating the status are one transaction." },
          { ja: "ただ、ジョブの作成とキューへの送信は、トランザクションではありません。", en: "But creating the job and sending to the queue are not transactional." },
          { ja: "送信に失敗したら、ジョブをFAILEDにして、画面から再試行{さいしこう}できます。", en: "If the send fails, the job is marked FAILED and can be retried from the UI." },
          { ja: "本格的{ほんかくてき}にやるなら、Outboxパターンを使うと思います。", en: "To do it properly, I'd use the outbox pattern." },
        ],
        tip: "Admitting the known gap (ADR 0001) and naming the outbox pattern is better than claiming everything is atomic.",
      },
      {
        q: { ja: "本番{ほんばん}では、どう運用する予定でしたか？", en: "How did you plan to run it in production?" },
        a: [
          { ja: "AWSでは、RDSのPostgreSQLを使う設計にしました。", en: "On AWS, I designed it to use RDS for PostgreSQL." },
          { ja: "Terraformで、プライベートサブネットに置く形で書いてあります。", en: "It's written in Terraform, placed in private subnets." },
          { ja: "ただ、AWSアカウントの審査{しんさ}が終わらず、まだデプロイしていません。", en: "But my AWS account verification never finished, so it isn't deployed." },
          { ja: "ローカルでは、同じPostgreSQL 16で動かしています。", en: "Locally it runs on the same PostgreSQL 16." },
        ],
        tip: "Be honest and brief about the AWS block. Never imply RDS was running in production.",
      },
    ],
    videoSearch: ["PostgreSQL 入門 解説", "楽観的ロック 悲観的ロック 違い", "Amazon RDS PostgreSQL 入門"],
    docs: [
      { title: "PostgreSQL 16 文書 (日本語)", url: "https://www.postgresql.jp/document/16/html/" },
      { title: "Amazon RDS for PostgreSQL (日本語)", url: "https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html" },
    ],
    related: ["prisma", "job-states", "idempotency", "worker", "terraform", "server-actions"],
  },

  // ── S3 ─────────────────────────────────────────────────────────
  {
    id: "s3",
    group: "data",
    name: "S3",
    ja: "オブジェクトストレージ",
    say: "エススリー",
    oneLiner: {
      ja: "素材{そざい}と書{か}き出{だ}した動画を置く場所で、ブラウザは署名付{しょめいつ}きURLで直接アップロードします。",
      en: "Where uploads and rendered videos live; the browser uploads straight to it with presigned URLs.",
    },
    explain: [
      { ja: "S3は、AWSのオブジェクトストレージです。", en: "S3 is AWS's object storage." },
      { ja: "アップロードした素材{そざい}と、書{か}き出{だ}したMP4を置いています。", en: "It holds uploaded media and the exported MP4s." },
      { ja: "ブラウザは、S3に直接アップロードします。", en: "The browser uploads directly to S3." },
      { ja: "サーバーは、署名付{しょめいつ}きURLを発行{はっこう}するだけです。", en: "The server only issues a presigned URL." },
      { ja: "アップロード用のURLは、10分で期限{きげん}が切れます。", en: "The upload URL expires after 10 minutes." },
      { ja: "その後、HeadObjectで本当にあるか確認します。", en: "Then HeadObject checks that the file is really there." },
      { ja: "再生{さいせい}とダウンロードには、署名付きのGET URLを使います。", en: "Playback and downloads use presigned GET URLs." },
      { ja: "ローカルでは、MinIOがS3の代わりをしています。", en: "Locally, MinIO stands in for S3." },
    ],
    why: [
      { ja: "2GBの動画を、Next.jsのメモリに通したくないからです。", en: "Because I don't want 2 GB videos passing through Next.js memory." },
      { ja: "コードはAWS SDKのままで、エンドポイントだけ切{き}り替{か}えます。", en: "The code stays on the AWS SDK; only the endpoint changes." },
      { ja: "トレードオフは、URLの署名とエンドポイントの設定が少しややこしいことです。", en: "The trade-off is that URL signing and endpoint settings get a bit fiddly." },
      { ja: "サーバー内部{ないぶ}の宛先{あてさき}と、ブラウザから見える宛先が違うからです。", en: "Because the in-cluster address differs from the one the browser can reach." },
    ],
    status: "local",
    statusNote: "The code uses the AWS SDK v3 S3 client and presigned URLs, but it has only run against MinIO (Docker Compose and kind); the S3 bucket and CloudFront exist only in the Terraform sketch.",
    inRepo: [
      { path: "apps/web/lib/storage.ts", what: "Presigned PUT/GET, HeadObject, separate in-cluster and public endpoints, and the signed-URL reuse cache." },
      { path: "packages/core/src/keys.ts", what: "Object key layout: uploads/, thumbs/, and renders/<jobId>.mp4 for idempotent output." },
      { path: "apps/web/components/editor/upload.ts", what: "The browser side: PUTs the file and thumbnail straight to storage." },
      { path: "docker-compose.yml", what: "MinIO (Chainguard image) and ElasticMQ as local stand-ins." },
    ],
    terms: [
      { ja: "オブジェクトストレージ", en: "object storage" },
      { ja: "バケット", en: "bucket" },
      { ja: "オブジェクトキー", en: "object key" },
      { ja: "署名付{しょめいつ}きURL", en: "presigned URL", note: "プリサインドURL is also common." },
      { ja: "有効期限{ゆうこうきげん}", en: "expiry / validity period" },
      { ja: "直接{ちょくせつ}アップロード", en: "direct upload" },
      { ja: "エンドポイント", en: "endpoint" },
      { ja: "S3互換{ごかん}", en: "S3-compatible", note: "MinIO is S3互換のストレージ." },
      { ja: "冪等性{べきとうせい}", en: "idempotency", note: "Output key depends only on the job id, so a duplicate render overwrites the same object." },
      { ja: "発行{はっこう}する", en: "to issue (a URL, a token)" },
    ],
    qa: [
      {
        q: { ja: "なぜブラウザから直接アップロードするんですか？", en: "Why upload directly from the browser?" },
        a: [
          { ja: "動画は最大{さいだい}2GBあります。", en: "Videos can be up to 2 GB." },
          { ja: "Webサーバーのメモリを通す理由がありません。", en: "There's no reason to pass them through the web server's memory." },
          { ja: "Server Actionsには、ボディサイズの制限{せいげん}もあります。", en: "Server Actions also have a body size limit." },
          { ja: "なので、サーバーは検証{けんしょう}して、署名付{しょめいつ}きURLを返すだけです。", en: "So the server only validates and returns a presigned URL." },
          { ja: "アップロード後に、HeadObjectで存在{そんざい}を確認してから登録します。", en: "After the upload, it confirms the object with HeadObject before recording it." },
        ],
        tip: "Mention the two-step flow (createUpload, then confirmUpload). The server never decodes media; the browser measures duration and makes the thumbnail.",
      },
      {
        q: { ja: "署名付きURLで、ハマったことはありますか？", en: "Any gotchas with presigned URLs?" },
        a: [
          { ja: "はい、いくつかありました。", en: "Yes, a few." },
          { ja: "まず、署名はブラウザから見えるホスト名で作る必要があります。", en: "First, the signature must be made for the host the browser can reach." },
          { ja: "なので、サーバー用と署名用で、クライアントを二つ作りました。", en: "So I made two clients: one for server calls, one for signing." },
          { ja: "次に、SDKのチェックサムヘッダーを、ブラウザは送れません。", en: "Next, the browser can't send the SDK's checksum headers." },
          { ja: "最後に、同じキーでも署名のたびにURLが変わって、動画が読み直されました。", en: "Finally, each signing gives a new URL, which made videos reload." },
        ],
        tip: "Specific war stories show you really built it. All three fixes are in apps/web/lib/storage.ts.",
      },
      {
        q: { ja: "AWSのS3は、実際{じっさい}に使いましたか？", en: "Did you actually use AWS S3?" },
        a: [
          { ja: "ReelWalkでは、まだ本物のS3にはデプロイしていません。", en: "For ReelWalk, I haven't deployed to real S3 yet." },
          { ja: "AWSアカウントの審査{しんさ}が終わらなかったためです。", en: "Because my AWS account verification didn't finish." },
          { ja: "ローカルではMinIOを使って、同じAWS SDKで動かしました。", en: "Locally I used MinIO, with the same AWS SDK." },
          { ja: "本番{ほんばん}では、環境変数{かんきょうへんすう}を変えるだけで切り替わる設計です。", en: "In production it's designed to switch by changing environment variables only." },
        ],
        tip: "Honesty is the point here. Then pivot to what you did verify locally.",
      },
    ],
    videoSearch: ["Amazon S3 署名付きURL 解説", "S3 presigned URL アップロード", "MinIO 入門 S3互換"],
    docs: [
      { title: "署名付き URL の使用 (Amazon S3 ユーザーガイド)", url: "https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/userguide/using-presigned-url.html" },
      { title: "Amazon S3 とは (日本語)", url: "https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/userguide/Welcome.html" },
    ],
    related: ["server-actions", "cloudfront", "worker", "idempotency", "iam-secrets", "terraform"],
  },

  // ── Turborepo ──────────────────────────────────────────────────
  {
    id: "turborepo",
    group: "delivery",
    name: "Turborepo",
    ja: "モノレポのタスク実行",
    say: "ターボレポ",
    oneLiner: {
      ja: "モノレポのタスクを、依存関係{いぞんかんけい}の順にキャッシュ付きで実行します。",
      en: "Runs the monorepo's tasks in dependency order, with caching.",
    },
    explain: [
      { ja: "[Turborepo]{ターボレポ}は、モノレポ用のタスクランナーです。", en: "Turborepo is a task runner for monorepos." },
      { ja: "pnpmのワークスペースで、appsとpackagesを管理しています。", en: "apps and packages are managed as a pnpm workspace." },
      { ja: "typecheck、test、buildを、依存関係{いぞんかんけい}の順に実行します。", en: "It runs typecheck, test and build in dependency order." },
      { ja: "結果はキャッシュされるので、変更がなければすぐ終わります。", en: "Results are cached, so with no changes it finishes instantly." },
      { ja: "大事なのは、db:generateを最初に走らせることです。", en: "The key point is running db:generate first." },
      { ja: "Prismaのクライアントがないと、型チェックが通らないからです。", en: "Without the Prisma client, the type check fails." },
      { ja: "turbo.jsonのdependsOnで、この順番を書いています。", en: "turbo.json's dependsOn encodes that order." },
    ],
    why: [
      { ja: "Webとワーカーが、core、db、renderのパッケージを共有しているからです。", en: "Because web and worker share the core, db and render packages." },
      { ja: "順番を手で管理するのは、ミスのもとです。", en: "Managing the order by hand invites mistakes." },
      { ja: "トレードオフは、設定を間違えると古いキャッシュが使われることです。", en: "The trade-off is that a wrong config can serve a stale cache." },
      { ja: "db:generateにはinputsを書いて、スキーマが変わった時だけ再生成{さいせいせい}します。", en: "db:generate declares its inputs, so it regenerates only when the schema changes." },
    ],
    status: "built",
    statusNote: "Built: `pnpm typecheck/test/build` run through turbo locally and in GitHub Actions; caching is local only (no remote cache), and the Dockerfiles do not use turbo prune.",
    inRepo: [
      { path: "turbo.json", what: "The task graph: typecheck and test depend on db:generate and ^db:generate." },
      { path: "pnpm-workspace.yaml", what: "Workspace members: apps/*, packages/*, e2e." },
      { path: "package.json", what: "Root scripts that call turbo run typecheck/test/build." },
      { path: ".github/workflows/ci.yml", what: "CI runs pnpm lint, typecheck and test, which go through turbo." },
    ],
    terms: [
      { ja: "モノレポ", en: "monorepo" },
      { ja: "タスクランナー", en: "task runner" },
      { ja: "タスクグラフ", en: "task graph" },
      { ja: "依存関係{いぞんかんけい}", en: "dependency relationship" },
      { ja: "キャッシュヒット", en: "cache hit" },
      { ja: "リモートキャッシュ", en: "remote cache" },
      { ja: "ワークスペース", en: "workspace (pnpm)" },
      { ja: "並列実行{へいれつじっこう}", en: "parallel execution" },
      { ja: "再生成{さいせいせい}", en: "regeneration" },
    ],
    qa: [
      {
        q: { ja: "turbo.jsonの「^」は、何を意味{いみ}しますか？", en: "What does the ^ in turbo.json mean?" },
        a: [
          { ja: "依存{いぞん}しているパッケージの、同じタスクという意味です。", en: "It means the same task in the packages this one depends on." },
          { ja: "^db:generateなら、依存先{いぞんさき}のdb:generateを先に実行します。", en: "^db:generate runs db:generate in dependencies first." },
          { ja: "webの型チェックの前に、dbのgenerateが走ります。", en: "Before web's type check, db's generate runs." },
          { ja: "^がなければ、同じパッケージの中のタスクです。", en: "Without ^, it refers to a task in the same package." },
        ],
        tip: "A small syntax question that checks you actually wrote the config. Have turbo.json in your head.",
      },
      {
        q: { ja: "Turborepoを入れて、何が良くなりましたか？", en: "What improved after adding Turborepo?" },
        a: [
          { ja: "コマンド一つで、全部のパッケージをチェックできます。", en: "One command checks every package." },
          { ja: "Prismaのgenerate忘{わす}れが、なくなりました。", en: "Forgetting Prisma generate stopped happening." },
          { ja: "変更のないパッケージは、キャッシュで飛ばされます。", en: "Unchanged packages are skipped thanks to the cache." },
        ],
        tip: "Lead with the concrete problem it solved (generate ordering), not just \"it's faster\".",
      },
      {
        q: { ja: "リモートキャッシュは使っていますか？", en: "Do you use remote caching?" },
        a: [
          { ja: "今は使っていません。キャッシュはローカルだけです。", en: "Not now. The cache is local only." },
          { ja: "CIでは、pnpmのストアとDockerのレイヤーをキャッシュしています。", en: "In CI, I cache the pnpm store and Docker layers." },
          { ja: "チームで使うなら、リモートキャッシュを入れると思います。", en: "For a team, I'd add a remote cache." },
          { ja: "CIの時間が、かなり短くなるはずです。", en: "It should cut CI time considerably." },
        ],
        tip: "Honest scope, plus what you'd do on a team. Craftsman uses Turborepo, so expect follow-ups on caching.",
      },
    ],
    videoSearch: ["Turborepo 入門 解説", "モノレポ Turborepo pnpm", "Turborepo キャッシュ 仕組み"],
    docs: [
      { title: "Turborepo: Configuring tasks", url: "https://turborepo.com/docs/crafting-your-repository/configuring-tasks" },
      { title: "Turborepo: Caching", url: "https://turborepo.com/docs/crafting-your-repository/caching" },
      { title: "Turborepo: turbo.json reference", url: "https://turborepo.com/docs/reference/configuration" },
    ],
    related: ["prisma", "github-actions", "vitest", "docker", "typescript-react"],
  },
];
