import type { Video } from "../lib/types";

/**
 * Japanese-language YouTube videos, each verified via YouTube oEmbed.
 * `title` and `channel` are exactly what oEmbed returned (trailing whitespace trimmed).
 */
export const videos: Video[] = [
  // ── Next.js / React / TypeScript ─────────────────────────────────────────
  {
    id: "wUXGb_p4nDM",
    title: "#01【日本一わかりやすい Next.js App Router 入門】Pages Router 時代のメンタルモデルを破壊せよ",
    channel: "【トラハック】Webエンジニアリングを学ぶなら「とらゼミ」",
    topics: ["nextjs"],
    note: "A slow, clearly spoken opener explaining how App Router thinking differs from Pages Router, giving you the vocabulary to say why the app is built on App Router.",
    level: "intro",
  },
  {
    id: "_CLqYXMOuxg",
    title: "#04【日本一わかりやすい Next.js App Router 入門】Server Components とは何者か",
    channel: "【トラハック】Webエンジニアリングを学ぶなら「とらゼミ」",
    topics: ["nextjs", "server-components"],
    note: "You hear Server Components and the rendering strategies explained step by step in Japanese, the exact terms an interviewer will use when asking where your code runs.",
    level: "intermediate",
  },
  {
    id: "lOhUnyV5ho0",
    title: "#05【日本一わかりやすい Next.js App Router 入門】Client Components とServer Components を活用するための実装パターン",
    channel: "【トラハック】Webエンジニアリングを学ぶなら「とらゼミ」",
    topics: ["nextjs", "server-components"],
    note: "Walks through patterns for splitting Client and Server Components, useful for explaining your component boundaries in Japanese.",
    level: "intermediate",
  },
  {
    id: "lmY8bj0flJI",
    title: "#08【日本一わかりやすい Next.js App Router 入門】Server Actions と revalidate",
    channel: "【トラハック】Webエンジニアリングを学ぶなら「とらゼミ」",
    topics: ["nextjs", "server-actions"],
    note: "Covers Server Actions together with revalidation, so you can describe in Japanese how a form submit mutates data and refreshes the page.",
    level: "intermediate",
  },
  {
    id: "JE5xfZo7_Qc",
    title: "あなたは\"use client\"と\"use server\"をいつ使うべきか知っていますか？【ServerActionsまで解説】",
    channel: "プログラミングチュートリアル",
    topics: ["nextjs", "server-components", "server-actions"],
    note: "A popular explainer on when to write \"use client\" versus \"use server\", ending with Server Actions, which is a very likely interview question.",
    level: "intro",
  },
  {
    id: "X6haQpKrooM",
    title: "ReactとTypeScriptの相性が良すぎる理由を解説しよう",
    channel: "【トラハック】Webエンジニアリングを学ぶなら「とらゼミ」",
    topics: ["typescript-react"],
    note: "Explains why React and TypeScript fit well together, giving you natural phrases for justifying type safety in a Japanese interview.",
    level: "intro",
  },

  // ── Data: Prisma / PostgreSQL ────────────────────────────────────────────
  {
    id: "9mE1j1vzUAQ",
    title: "【Prisma入門】次世代ORMで簡単にデータベース管理ができるようになろう",
    channel: "プログラミングチュートリアル",
    topics: ["prisma"],
    note: "A beginner Prisma walkthrough covering schema, migrations and queries, so you hear how Japanese developers say ORM, マイグレーション and スキーマ.",
    level: "intro",
  },
  {
    id: "jQixbNlYZW0",
    title: "【Next.js】PrismaでSQLを書かずにCRUDを実装する方法",
    channel: "いっしー@Webエンジニアのプログラミング教室",
    topics: ["prisma", "nextjs"],
    note: "Builds CRUD in Next.js with Prisma, matching the stack you will describe, with plain spoken explanations of each step.",
    level: "intro",
  },
  {
    id: "u28vgPSKhTU",
    title: "【Part1】経験豊かな講師に訊く！ 2022年度版 PostgreSQL 入門 ～ PostgreSQL の概要・特徴・ライセンス・開発体制 ～",
    channel: "SRA OSS",
    topics: ["postgresql"],
    note: "A calm seminar-style overview of PostgreSQL's features and history, good for the vocabulary behind why you chose Postgres.",
    level: "intro",
  },

  // ── AWS overview and services ────────────────────────────────────────────
  {
    id: "rkW9RvmXMjM",
    title: "[初心者向け]30分で学ぶAWS #devio2021",
    channel: "クラメソチャンネル | AWSや生成AIなど技術やってみた",
    topics: ["aws"],
    note: "Classmethod's 30-minute AWS overview in clear conference Japanese, a quick way to absorb how the major services are named and grouped.",
    level: "intro",
  },
  {
    id: "uuK-VaQLrzg",
    title: "Amazon Simple Storage Service (Amazon S3) ユースケース編【AWS Black Belt】",
    channel: "Amazon Web Services Japan 公式",
    topics: ["s3"],
    note: "AWS Japan's official S3 session on typical use cases, with the standard Japanese terms for buckets, objects and storage classes.",
    level: "intermediate",
  },
  {
    id: "VutHE2vSvFo",
    title: "Amazon Simple Storage Service (Amazon S3) セキュリティ編【AWS Black Belt】",
    channel: "Amazon Web Services Japan 公式",
    topics: ["s3", "iam-secrets"],
    note: "Explains S3 access control, bucket policies and encryption, which helps when you explain presigned URLs and least-privilege access.",
    level: "intermediate",
  },
  {
    id: "avfc0gQ7X0A",
    title: "20190717 AWS Black Belt Online Seminar Amazon Simple Queue Service",
    channel: "Amazon Web Services Japan 公式",
    topics: ["sqs", "retries-dlq", "worker"],
    note: "The official AWS Japan SQS deep-dive (2019, still accurate) covering visibility timeout, DLQs and FIFO; it is the source of most Japanese SQS terminology.",
    level: "intermediate",
  },
  {
    id: "hT7Se0oFEkU",
    title: "SQS + Lambda という非同期処理黄金パターン再入門  | AWS Dev Day 2022 Japan #AWSDevDay",
    channel: "Amazon Web Services Japan 公式",
    topics: ["sqs", "worker", "retries-dlq", "idempotency"],
    note: "A conference talk on the queue-plus-worker pattern including retries, partial failures and duplicate delivery, closely matching how your worker consumes jobs.",
    level: "intermediate",
  },
  {
    id: "ibiuiapNE44",
    title: "【AWS SQS】ソリューションアーキテクト アソシエイト(SAA)徹底対策",
    channel: "AWS資格 対策講座",
    topics: ["sqs", "retries-dlq"],
    note: "A structured lecture on standard vs FIFO queues, long polling, visibility timeout and dead-letter queues, spoken slowly for exam learners.",
    level: "intro",
  },
  {
    id: "QNylm0CktHA",
    title: "Amazon CloudFront（基礎編）【AWS Black Belt】",
    channel: "Amazon Web Services Japan 公式",
    topics: ["cloudfront"],
    note: "The official CloudFront basics session, giving you the Japanese for edge locations, origins and caching when explaining video delivery.",
    level: "intermediate",
  },
  {
    id: "ed_7Nf-kAV4",
    title: "【0から始めるAWS入門】IAMって結局何？【IAMロール・ポリシー・ユーザー・グループ】",
    channel: "まりんとすふぃあ【駆け出しエンジニア系Vtuber】",
    topics: ["iam-secrets"],
    note: "A friendly beginner explanation of IAM roles, policies, users and groups, ideal for practising how to say who may do what.",
    level: "intro",
  },
  {
    id: "b8uReUdJBfM",
    title: "Amazon Bedrock Overview 【Amazon Bedrock Series #01】【AWS Black Belt】",
    channel: "Amazon Web Services Japan 公式",
    topics: ["bedrock"],
    note: "AWS Japan's Bedrock overview, so you can describe calling foundation models through a managed service in Japanese.",
    level: "intro",
  },
  {
    id: "fzVkJne3OMI",
    title: "Amazon CloudWatch の概要と基本【AWS Black Belt】",
    channel: "Amazon Web Services Japan 公式",
    topics: ["cloudwatch"],
    note: "Covers metrics, logs and alarms in CloudWatch, the vocabulary you need when talking about monitoring queue depth and worker errors.",
    level: "intro",
  },

  // ── Async: queues, idempotency, retries ──────────────────────────────────
  {
    id: "xK6kfNA25aI",
    title: "なぜシステムに「キュー」が必要なのか？非同期処理の基本から冪等性・詰まり監視まで解説",
    channel: "レイタのIT解説",
    topics: ["worker", "idempotency", "retries-dlq", "job-states"],
    note: "Explains why systems need a queue, then idempotency and monitoring for stuck jobs, which is almost exactly the async story you will tell.",
    level: "intro",
  },
  {
    id: "09QCbHPhLRY",
    title: "【エンジニア入門】冪等性とは？同じリクエストを2回送っても注文が重複しない仕組み",
    channel: "Good Software",
    topics: ["idempotency"],
    note: "A clear beginner explanation of 冪等性 using a duplicate-order example, so you can say べきとうせい confidently and give a concrete case.",
    level: "intro",
  },
  {
    id: "s0xZy9-Q_Gk",
    title: "【リトライすれば直ると思ってない？】外部 API 呼び出しの作法をこの動画一本で - タイムアウト・リトライ・冪等性・maxSockets・fd上限",
    channel: "フルスタックLinuxプログラミング",
    topics: ["retries-dlq", "idempotency"],
    note: "A deeper talk on timeouts, retries and idempotency when calling external APIs, good for answering follow-up questions about safe retries.",
    level: "deep",
  },

  // ── Platform: Docker / Kubernetes / Helm / EKS ───────────────────────────
  {
    id: "lZD1MIHwMBY",
    title: "Docker超入門講座 合併版 | ゼロから実践する4時間のフルコース",
    channel: "だれでもエンジニア / 山浦清透",
    topics: ["docker"],
    note: "A very popular, slowly paced Docker course; dip into the early chapters for images, containers and Dockerfile vocabulary.",
    level: "intro",
  },
  {
    id: "iAW6gfbvPMQ",
    title: "Kubernetes 超入門",
    channel: "Japan Oracle Developers",
    topics: ["kubernetes"],
    note: "A seminar-style introduction to containers, orchestration and core Kubernetes objects, delivered at a measured pace.",
    level: "intro",
  },
  {
    id: "ANK-JGgEcv8",
    title: "第96回 雲勉【オンライン：初心者向け】インフラエンジニアの Kubernetes 入門",
    channel: "KDDIアイレット株式会社",
    topics: ["kubernetes"],
    note: "A beginner study session on Kubernetes architecture and main components, useful for hearing Pod, Deployment and Service used in Japanese sentences.",
    level: "intro",
  },
  {
    id: "_iBzbiMk9E4",
    title: "Kubernetes 入門 (IIJ Bootcamp 2023)",
    channel: "IIJPR",
    topics: ["kubernetes"],
    note: "IIJ's new-hire bootcamp lecture on Kubernetes fundamentals, structured like a class with clear explanations of why Kubernetes exists.",
    level: "intro",
  },
  {
    id: "VFnVHqmS0fA",
    title: "【Kubernetes入門】Helmチャートとは？仕組みと基本構成を徹底解説（Podcast vol.7）",
    channel: "Everyday Podcast",
    topics: ["helm", "kubernetes"],
    note: "A podcast-style explanation of Helm charts using a recipe analogy, so you can explain charts, values and templates simply.",
    level: "intro",
  },
  {
    id: "E5TEqZhS0D0",
    title: "Amazon Elastic Kubernetes Service(Amazon EKS) 入門【AWS Black Belt】",
    channel: "Amazon Web Services Japan 公式",
    topics: ["eks", "kubernetes"],
    note: "AWS Japan's EKS introduction covering the managed control plane, node groups and integrations, the language you need to explain the EKS design.",
    level: "intro",
  },

  // ── Delivery: GitHub Actions / Argo CD / Terraform / Trivy / Turborepo ──
  {
    id: "Tzj9fHVazuI",
    title: "【超入門】GitHub Actionsを分かりやすくサクッと解説",
    channel: "GEECHS JOBーギークスジョブ",
    topics: ["github-actions"],
    note: "A short, plain introduction to workflows, jobs and triggers, ideal for warming up CI vocabulary.",
    level: "intro",
  },
  {
    id: "BgAEznr7-GQ",
    title: "GitHub Actions入門を10分で解説 CI/CD・workflow・checkout・secrets・OIDCまで",
    channel: "フレブルと学ぶ「AI」のあれこれ",
    topics: ["github-actions", "iam-secrets"],
    note: "Ten minutes on workflows, secrets and OIDC, which helps you explain keyless AWS access from CI in Japanese.",
    level: "intro",
  },
  {
    id: "-1Nd0CmoN7o",
    title: "「みんなの銀行」のモダンな開発基盤を支えるアーキテクチャと ArgoCD による自動化戦略",
    channel: "Google Cloud Japan",
    topics: ["argocd", "kubernetes"],
    note: "A real-world Japanese case study of GitOps with Argo CD at a bank, giving you natural phrasing for describing declarative, Git-driven deployment.",
    level: "intermediate",
  },
  {
    id: "iR1MDGE2aL8",
    title: "【Terraform講座-1】はじめに/IaCのメリット/AWSで利用されるIaCツール /Terraform概要/リソースの作成、変更、削除",
    channel: "CloudTech",
    topics: ["terraform"],
    note: "An AWS-focused Terraform lesson on IaC benefits and the plan/apply lifecycle, matching how you would describe the Terraform in the repo.",
    level: "intro",
  },
  {
    id: "3etJaWzGSpk",
    title: "第99回 雲勉 Infrastructure as Code (IaC) 入門 〜TerraformとAnsibleを使ってみよう〜",
    channel: "KDDIアイレット株式会社",
    topics: ["terraform"],
    note: "A beginner study session comparing Terraform and Ansible, useful for explaining what IaC is and why declarative infrastructure matters.",
    level: "intro",
  },
  {
    id: "GktLZIZkKUY",
    title: "【STAC2024】GitHub Actions上でコンテナ脆弱性スキャンを自動化した話 / 河田鷹介さん #stac2024",
    channel: "テスト自動化研究会",
    topics: ["trivy", "github-actions", "docker"],
    note: "A conference talk on automating container vulnerability scanning with Trivy in GitHub Actions, almost exactly what your CI pipeline does.",
    level: "intermediate",
  },
  {
    id: "8sm1VmOg9OE",
    title: "【初心者向け】脆弱性って何？なんでバージョンを上げないといけないの？【trivy】",
    channel: "kurenaif",
    topics: ["trivy"],
    note: "A beginner explanation of what a 脆弱性 is and why dependency upgrades matter, demonstrated with Trivy.",
    level: "intro",
  },
  {
    id: "PdzUyR5YDFA",
    title: "Vercel製のTurborepoでモノレポの開発を快適に！？",
    channel: "クロノITチャンネル",
    topics: ["turborepo"],
    note: "A Japanese introduction to Turborepo and monorepos, so you can explain task caching and workspace packages.",
    level: "intro",
  },

  // ── Quality: Vitest / Playwright ─────────────────────────────────────────
  {
    id: "3uLXoCjSiNI",
    title: "【ライブ勉強会】Vitestではじめるソフトウェアテスト入門",
    channel: "REDIMPULZ Lab [レッドインパルス・ラボ]",
    topics: ["vitest"],
    note: "A live study session introducing unit testing with Vitest, with explanations of テストケース, アサーション and モック.",
    level: "intro",
  },
  {
    id: "kLOss2qjm_I",
    title: "【Playwright入門】Webテスト自動化でE2Eテストを効率化！導入から基本操作まで解説",
    channel: "KENのモダンWeb開発ラボ",
    topics: ["playwright"],
    note: "Explains why E2E tests matter and how to write a first Playwright test, giving you the Japanese to describe your browser test suite.",
    level: "intro",
  },

  // ── Remotion ─────────────────────────────────────────────────────────────
  {
    id: "o7hgmeQycEk",
    title: "【Remotion入門】Reactで動画を作る！コードで量産できる仕組みを20分で徹底解説",
    channel: "ニアと魔王の知識探究ラボ",
    topics: ["remotion", "typescript-react"],
    note: "A 20-minute overview of making video with React in Remotion, helping you explain how the reels are rendered from code.",
    level: "intro",
  },

  // ── Interview Japanese ───────────────────────────────────────────────────
  {
    id: "bF4mWaL0MjQ",
    title: "ITエンジニアの「転職面接」は99％この流れで進みます！",
    channel: "ITエンジニアch【ESES社長・白川】",
    topics: ["interview"],
    note: "Walks through the typical order of a Japanese engineer interview, so nothing in the flow surprises you on the day.",
    level: "intro",
  },
  {
    id: "31C5q7HKsI4",
    title: "ITエンジニア面接でよく聞かれる質問と対策を徹底解説！",
    channel: "ITサプリ",
    topics: ["interview"],
    note: "Common engineer interview questions with how to approach each, good listening practice for the exact question phrasing.",
    level: "intro",
  },
  {
    id: "5hC2A4jpgMU",
    title: "🇯🇵 【N1/N2】 ITエンジニア面接対策｜自己紹介・志望動機・日本で働きたい理由",
    channel: "Japanese Job Interview - にほんのめんせつ",
    topics: ["interview"],
    note: "Made for N1/N2 learners: model answers for 自己紹介, 志望動機 and why you want to work in Japan, spoken at learner-friendly speed.",
    level: "intro",
  },
  {
    id: "KuMsXrmuZlE",
    title: "【外国人エンジニア面接対策】 外国籍エンジニアの面接練習 質問内容：日本で働きたい理由",
    channel: "glotecチャンネル",
    topics: ["interview"],
    note: "Interview practice aimed at foreign engineers on the question of why you want to work in Japan, with feedback on what interviewers look for.",
    level: "intro",
  },
  {
    id: "2iaTXPG94bs",
    title: "【外国籍エンジニア向け 面接練習】面接で「何か質問はありますか？」と聞かれたときの模範回答例とNG回答の違いとは！？",
    channel: "glotecチャンネル",
    topics: ["interview"],
    note: "Model and bad answers to 何か質問はありますか for foreign engineers, so your 逆質問 sounds natural and well prepared.",
    level: "intro",
  },
  {
    id: "wBZPZGYfySA",
    title: "【ITエンジニア転職/就職】おすすめ逆質問5選！採用面接時には〇〇を聞け！【現役採用担当が解説】",
    channel: "ITサプリ",
    topics: ["interview"],
    note: "A recruiter's five recommended 逆質問 for engineer interviews, giving you ready-made questions to adapt for the end of the interview.",
    level: "intro",
  },
  {
    id: "B2d_e4ajfgY",
    title: "未経験がハマる落とし穴！面接で必ず聞かれる技術選定攻略3選",
    channel: "エンジニア転職チャンネル【RUNTEQ公式】",
    topics: ["interview"],
    note: "Explains how to answer 技術選定 questions (why this technology), which you will face for every tool in the stack.",
    level: "intro",
  },
];
